replicaCount: 1

frontend:
  name: map-viewer-frontend
  group: map-viewer
  path: /
  tls:
    fqdn: map-viewer.k8s.ucar.edu
    secretName: incommon-cert-map-viewer
  container: 
    image: docker.io/mattrncar/map-viewer-frontend:v1
    port: 80
    memory: 1G
    cpu: 2
backend:
  name: map-viewer-backend
  group: map-viewer
  container: 
    image: docker.io/mattrncar/map-viewer-backend:v1
    port: 8000
    memory: 1G
    cpu: 2
