apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.frontend.group }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - {{ .Values.frontend.tls.fqdn }}
      secretName: {{ .Values.frontend.tls.secretName }}
  rules:
  - host: {{ .Values.frontend.tls.fqdn }}
    http:
      paths:
      - path: {{ .Values.frontend.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.container.port }}
